### ISSUE TITLE
Latest update breaks the bot

### ISSUE THREAD

**Issue by rpasta42** [McSwaggens/linux-csgo-external#1]
Seems like Valve is releasing updates for executables a lot faster than in the past.

What is the process for reverse-engineering and finding the offsets and addresses for every new executable update? I want to try learning and document the process.

**Comment by bryantwilliam** [comment]
Google?

**Comment by rpasta42** [comment]
Your comment is unproductive and adds nothing to discussion. This information isn't easily obtainable through google, but instead requires understand of the game itself and the structure of the hack.

I've been going over the code for few hours, but still struggling to understand the method for obtaining addresses. 

So far, I gathered that the address is not hardcoded, but gets detected from a search for a specific pattern of bytes in main.cpp.

This version of the hack looks for a lot more addresses than the original, due to the triggerbot and bunnyhop bot. I would like to understand how those patterns are obtained, and where to look for data structures changes of internal game objects. IDA Pro? Cheat Engine type thing? Other reverse engineering methods?

I'll spend more time tomorrow and hopefully will be able to make more progress.

**Comment by McSwaggens** [comment]
I initially thought it would have been the client_client.so not being scanned correctly, but it seems like it's still finding the correct address, maybe the offsets have changed?

**Comment by WolverinDEV** [comment]
On my pc is all working. Only the XRay not.

**Comment by McSwaggens** [comment]
XRay has now been fixed in [this commit](https://github.com/McSwaggens/linux-csgo-external/commit/9b2e5be1698e560cb05205acedded47064b6f4d5)

**Comment by WolverinDEV** [comment]
Thanks <3

**Comment by bryantwilliam** [comment]
Sorry, I thought this was actually a direct email to me, not github. :PThis is because people privately email me about the hack all the time and I dont play csgo anymore.

**Comment by rpasta42** [comment]
No problem. I'm trying to kick the habit too, but CS is too damn addictive. Hopefully all this hacks will either make me bored of the game and quit, or I get VAC banned.

**Comment by McSwaggens** [comment]
I highly doubt you will get banned for using this hack, I'm sure you've seen around the place, VAC is virtually non existent on Linux, however, you can still get banned through overwatch.

**Comment by bryantwilliam** [comment]
Off topic: Btw McSwaggens? I was smurfing like last week and saw your an account with your profile picture on aus servers. Was that you? I asked if it was you but the person didn't respond.

@rpasta42 I do still play now and then, but I don't hack because it made me feel like shit for winning. I'm an LEM legit with no hacks. I only play like once a week now though since Dota 2 is my new game.

**Comment by McSwaggens** [comment]
None of my accounts have my github picture, but I do play on Australian servers so if you'd like to add me [here](http://steamcommunity.com/profiles/76561198325262721/) is the smurf I currently play on.

**Comment by bryantwilliam** [comment]
Added. This is my smurf: http://steamcommunity.com/profiles/76561198267634005/ and my LEM account: http://steamcommunity.com/id/XYZUNKNOWNXYZ
