### ISSUE TITLE
Need help making aimbot

### ISSUE THREAD

**Issue by McSwaggens** [McSwaggens/linux-csgo-external#10]
If someone wants to find the `ClientState` pointer inside of `engine_client.so` ([here](https://github.com/McSwaggens/linux-csgo-external/blob/master/remote.h#L59)), I can start the process of writing an aimbot, the only real offset I need as of this moment to `ClientState` is `ViewAngleRotation`.

Any help would be appreciated, cheers!

**Comment by crazywolf132** [comment]
How about no.

**Comment by faminee** [comment]
I would help you out writing the aimbot, but I don't know C that well...
I will try to get you the offset when I'm free.

**Comment by faminee** [comment]
Any progress on aim? I think I found an open source aim for linux before, you can grab the offsets from there.

Maybe spinbot?

**Comment by AntoninataRiech** [comment]
If you mean vcaim, that's 32-bit with totally different offsets from 3 months ago :)

**Comment by faminee** [comment]
Yeah. I found it and it was outdated.

**Comment by AntoninataRiech** [comment]
BTW, How do you plan to make an external spinbot (Not saying it's impossible, just saying it's easier to do it internally)

**Comment by McSwaggens** [comment]
> BTW, How do you plan to make an external spinbot

Considering someone can help me get signatures,
It would be in three parts
1. Make a small aim assist aimbot that should only require `ClientState` to get us started.
2. If we get an engine call for a `Ray Trace` function, we can do a rage aimbot.
3. If we get that far, we can also do packet sending to the game server, allowing us to fake positions and create a `spinbot`

I would love to do all of this, and I have the know how to do it in code but getting the signatures is another story, hopefully someone here knows how to use IDA!

**Comment by AntoninataRiech** [comment]
Look, I understand that. I'm just saying it'll be messy and not as handy as a normal internal. If you need a base, Atex created one here : [Internal Base Hook](http://www.unknowncheats.me/forum/counterstrike-global-offensive/181878-linux-basehook.html)

**Comment by McSwaggens** [comment]
Personally, I don't trust internal hacks on Linux opposed to external, where the process is unable to be scanned by VAC because of the permission level of the process.

Besides, I would still have the same problem ;)

**Comment by AntoninataRiech** [comment]
That is true, but so far VAC hasn't scanned for memory writing/editing

**Comment by ozwaldorf** [comment]
there is no VAC for linux @McSwaggens

**Comment by AntoninataRiech** [comment]
The5heepDev, a lot may say so, but there is no proof of if there is or not.

**Comment by ozwaldorf** [comment]
@AntoninataRiech Someone did, but i forget where

**Comment by AntoninataRiech** [comment]
Someone did what?

**Comment by ozwaldorf** [comment]
A scan for vac

**Comment by AntoninataRiech** [comment]
You can't go off of what if VAC was there what it would do, because you don't know how VAC would be on linux.

**Comment by AntoninataRiech** [comment]
And yes, on the cheat forum unknowncheats did "prove" that VAC did exist for linux because it did not scan for memory writing, but that does not prove that VAC is nonexistent.

**Comment by AntoninataRiech** [comment]
On Linux atleast

**Comment by ozwaldorf** [comment]
@McSwaggens Is it possible to make a lag switch hack? I saw nick bunyan do a video on a hacker with one, [youtube link here](https://www.youtube.com/watch?v=flgSyqpUgqY) ,and it looks like a interesting idea to have.

**Comment by AntoninataRiech** [comment]
It's FakeLag.

**Comment by ozwaldorf** [comment]
@AntoninataRiech doesnt matter what it's called. How feasible is it to code?

**Comment by AntoninataRiech** [comment]
"aight

so the server receives usercmds from your client when doing networking. it puts them into an array.

when doing physics simulation, the server checks that array for any usercmds from you, and if there are some it runs them- doing movement for you, for one tick.

now, if you send more usercmds than 1 per tick, the server would normally do extra movement for you. this is how you speedhack, and it was patched.

but, because of networking flaws and the possibility of a low cl_cmdrate, you can temporarily have many usercmds processed in one server tick, if and only if you haven't sent usercmds recently. in other words, you have to send them ON AVERAGE once per tick, but you can vary the actual rate you send them.

If you send 0 usercmds for around 12 ticks, then send 12 usercmds all at once, you will move 12-ticks worth of motion in one server frame. to other players, you'll appear to be teleporting around. EstimateAbsVelocity will get fucked up by this and not return your actual velocity- because of that, predictive aimbots will not hit you correctly. But even against non-predictive aimbot, this teleporting lets you go from "behind a corner, no hitbox visible" to "visible, can hit enemy" in one server frame. Any aimbot without clever coding will never have a chance to shoot you- by the time you're visible, at all, they are already dead." Wittek 

[[Help]FakeLag](http://www.unknowncheats.me/forum/counterstrike-global-offensive/132967-fake-lag.html)

**Comment by AntoninataRiech** [comment]
Something like this? https://youtu.be/I5QyNA6H6rY

**Comment by ozwaldorf** [comment]
exactly

**Comment by AntoninataRiech** [comment]
I've tried it before, but the server just puts you back to your last saved position if you go off for that long :/

**Comment by ozwaldorf** [comment]
What about 1-2 seconds? thats all it takes to go round a corner anyways

**Comment by AntoninataRiech** [comment]
Not enough to give you an advantage, but as you saw in Nick's video. That works just fine.

**Comment by ozwaldorf** [comment]
I would imagine seeing someone lagging around like that would be hard to hit. How smooth is it for you? How smooth are other players?

**Comment by AntoninataRiech** [comment]
Other players are fine, but they can still hit your old position in between those 2 seconds which sucks.

**Comment by ozwaldorf** [comment]
Even when lagging around like in nicks video?

**Comment by AntoninataRiech** [comment]
Yes, even then.

**Comment by McSwaggens** [comment]
The point I was trying to make @The5heepDev, was that even **IF** VAC was implemented on Linux, the only permissions it would have access to read would be it's own process (Injected .so's) and **NOT** external hacks.

**Comment by faminee** [comment]
Any progress on aim hack?
Wasn't on for a few days.

**Comment by faminee** [comment]
Yup, trying to figure out ida myself rn

**Comment by McSwaggens** [comment]
Thinking about moving to LinuxBaseHook, but can't get it to inject :rage:  :rage:  :rage:

**Comment by AntoninataRiech** [comment]
Yay, good. I had a problem injecting too, fixed now. Do you need help?

**Comment by McSwaggens** [comment]
http://steamcommunity.com/profiles/76561198033827209/

**Comment by faminee** [comment]
? Why link us that vac'd account?
Did you fix the hook?

**Comment by AntoninataRiech** [comment]
Yeah, do you need help, or...?

**Comment by faminee** [comment]
I'm trying to setup a "ragehack", but I have no experience in cs hacks.

**Comment by McSwaggens** [comment]
@AntoninataRiech Would be appreciated.
@MrWhiteGoat The VAC bans are from other games, chill...

**Comment by faminee** [comment]
Yeah Ik, just why send to us xd

**Comment by AntoninataRiech** [comment]
(As root)
https://github.com/vikasnkumar/hotpatch
make install

hotpatcher -l $(pwd)/BasehookLinux.so -vvv $(pidof csgo_linux64)

**Comment by McSwaggens** [comment]
@AntoninataRiech http://pastebin.com/NBFqZHKV
