### ISSUE TITLE
Remove hack log

### ISSUE THREAD

**Issue by faminee** [McSwaggens/linux-csgo-external#13]
You should be able to remove hacklog, because it has no purpose tbh.
It just spams out

Hack loaded...

**Comment by AntoninataRiech** [comment]
Then remove it.

**Comment by McSwaggens** [comment]
Some people are suggesting a GUI, so when it's implemented we will need to use the log, but as of this moment, if you'd like to get rid of the logging (not that hard) try and do it yourself.
You'd just need to remove the the `Log.cpp`, `Log.h` and the lines it's used in `main.cpp`.

**Comment by faminee** [comment]
Just made my own fork, if anyone wants to use while the GUI is not done yet :)
