### ISSUE TITLE
Help

### ISSUE THREAD

**Issue by faminee** [McSwaggens/linux-csgo-external#14]
Hey, just wanted to know how would you get the offsets for cs while running linux?
I used to do it with cheatengine but I'm currently on my arch.

**Comment by AntoninataRiech** [comment]
scanmem, or the GUI version called GameConquerer. If at any point you don't understand, go on the cheat forum unknowncheats.me and there should be a tut on it or just ask.

**Comment by MrWhiteGoat** [comment]
Thx, I was trying out some shit. I used gameconquerer to get the address for a bots health, but didn't go far after that...

I'm going to look up a tut later :)
