### ISSUE TITLE
error 

### ISSUE THREAD

**Issue by ghost** [McSwaggens/linux-csgo-external#17]

**Comment by ghost** [comment]
ok i hate my num enter xD i got a error when i try to compile :D CMake Error at CMakeLists.txt:8 (add_executable):
  Cannot find source file:

```
log.cpp
```

  Tried extensions .c .C .c++ .cc .cpp .cxx .m .M .mm .h .hh .h++ .hm .hpp
  .hxx .in .txx

CMake Error: CMake can not determine linker language for target: csgo_external
CMake Error: Cannot determine link language for target "csgo_external".

CMakeFiles/csgo_external.dir/hack.cpp.o: In Funktion `hack::Glow(remote::Handle*, remote::MapModuleMemoryRegion*)':
hack.cpp:(.text+0x335): Nicht definierter Verweis auf`Logger::error(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >)'
hack.cpp:(.text+0x3e1): Nicht definierter Verweis auf `Logger::error(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >)'
CMakeFiles/csgo_external.dir/main.cpp.o: In Funktion`main':
main.cpp:(.text+0x1c): Nicht definierter Verweis auf `Logger::init()'
main.cpp:(.text+0xa3): Nicht definierter Verweis auf`Logger::error(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >)'
main.cpp:(.text+0x430): Nicht definierter Verweis auf `Logger::normal(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >)'
main.cpp:(.text+0x4b8): Nicht definierter Verweis auf`Logger::error(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >)'
main.cpp:(.text+0x679): Nicht definierter Verweis auf `Logger::error(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >)'
main.cpp:(.text+0x6f2): Nicht definierter Verweis auf`Logger::address(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, unsigned long)'
main.cpp:(.text+0x753): Nicht definierter Verweis auf `Logger::address(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, unsigned long)'
main.cpp:(.text+0x823): Nicht definierter Verweis auf`Logger::address(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, unsigned long)'
main.cpp:(.text+0x8ab): Nicht definierter Verweis auf `Logger::address(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, unsigned long)'
main.cpp:(.text+0xa82): Nicht definierter Verweis auf`Logger::address(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, unsigned long)'
CMakeFiles/csgo_external.dir/main.cpp.o:main.cpp:(.text+0xb59): Weitere nicht definierte Verweise auf `Logger::address(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, unsigned long)' folgen
CMakeFiles/csgo_external.dir/main.cpp.o: In Funktion`main':
main.cpp:(.text+0xcdc): Nicht definierter Verweis auf `Logger::toggle(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, bool)'
main.cpp:(.text+0xd62): Nicht definierter Verweis auf`Logger::toggle(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, bool)'
main.cpp:(.text+0xdeb): Nicht definierter Verweis auf `Logger::toggle(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, bool)'
main.cpp:(.text+0xe7c): Nicht definierter Verweis auf`Logger::toggle(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, bool)'
collect2: error: ld returned 1 exit status
CMakeFiles/csgo_external.dir/build.make:172: die Regel für Ziel „build/csgo_external“ scheiterte
make[2]: **\* [build/csgo_external] Fehler 1
CMakeFiles/Makefile2:67: die Regel für Ziel „CMakeFiles/csgo_external.dir/all“ scheiterte
make[1]: **\* [CMakeFiles/csgo_external.dir/all] Fehler 2
Makefile:83: die Regel für Ziel „all“ scheiterte
make: **\* [all] Fehler 2

**Comment by luk1337** [comment]
https://github.com/McSwaggens/linux-csgo-external/pull/18
