### ISSUE TITLE
GLOW 

### ISSUE THREAD

**Issue by ghost** [McSwaggens/linux-csgo-external#2]
Glow dosent work i think new offsets idk maybe look for that mfg Sandro :)

**Comment by McSwaggens** [comment]
Working on it :100: :ok_hand:

**Comment by WolverinDEV** [comment]
The list offset has moved... can you tell how do you find the offsets? Im very interisted in stuff like this

**Comment by ghost** [comment]
nop
i can send you a screen the glow not work

**Comment by ghost** [comment]
ah you update this nice work man :)
