### ISSUE TITLE
TriggerBot

### ISSUE THREAD

**Issue by INeedHelpNoob** [McSwaggens/linux-csgo-external#23]
It would be good if you could change the triggerbot speed or the delay of the shots to be quicker. E.G change the sleep ms to like 1ms or the after fire delay to 1ms

**Comment by AntoninataRiech** [comment]
Then change it in a fork and merge. Or do just keep it on yours, it's not hard.

**Comment by McSwaggens** [comment]
You can change the delay of the trigger bot [here](https://github.com/McSwaggens/linux-csgo-external/blob/master/hack.cpp#L105) if you want.

I was thinking about implementing a config file in the near future.

**Comment by INeedHelpNoob** [comment]
Would be good to have a key for noflash

**Comment by luk1337** [comment]
We have a key for no flash. It's F8.

**Comment by INeedHelpNoob** [comment]
Luk Cheers

**Comment by INeedHelpNoob** [comment]
I'm sorry for being a bit of a noob

**Comment by AntoninataRiech** [comment]
Close thread?
