### ISSUE TITLE
triggerbot broken with todays update

### ISSUE THREAD

**Issue by nopenothingever** [McSwaggens/linux-csgo-external#25]
as title says, csgo updated today and triggerbot is no longer working.
Glow esp is working though :)

**Comment by McSwaggens** [comment]
`crossHairID` offset has been changed

**Comment by WolverinDEV** [comment]
can you fix that?

**Comment by Goldstrikerz** [comment]
Updated value for mac OS X is the same:

crosshairID = 0xB380;

So I don't think this is the issue

**Comment by AntoninataRiech** [comment]
It is, he's just still working on it. Be patient.

**Comment by McSwaggens** [comment]
Trigger bot has been fixed in [this](https://github.com/McSwaggens/linux-csgo-external/commit/d90914d7f56b9ae80cf533f3f0e561d817ec1ade) commit
