### ISSUE TITLE
Configuration File

### ISSUE THREAD

**Issue by ghost** [McSwaggens/linux-csgo-external#27]
A config file for things like the RGB values of the glow and maybe keybinds for the features would be nice to have. Right now if you want to change those things you'll need to modify the source files which will get overwritten/possibly cause merging issues if a commit is pushed and you want that change.

**Comment by McSwaggens** [comment]
I've been thinking about doing this for a while now, haven't had time to do it recently but it wouldn't be that hard to implement.

**Comment by ghost** [comment]
Yeah, I might be able to do this in a few days once I'm on Linux (currently on Windows right now) and have some spare time. [vcaim](https://gitgud.io/vc/vcaim/blob/master/src/program.cpp) has some basic file reading code written already which could be helpful if anyone else wants to do it.

**Comment by faminee** [comment]
Going to do on Saturday probably.

**Comment by luk1337** [comment]
https://github.com/McSwaggens/linux-csgo-external/pull/29

**Comment by MrWhiteGoat** [comment]
Gj. I wrote it myself, but didn't finish...

**Comment by faminee** [comment]
Gj, I did a file parser on local, but didn't commit.

**Comment by ghost** [comment]
closing this as the PR was merged
