### ISSUE TITLE
Untrusted?

### ISSUE THREAD

**Issue by ghost** [McSwaggens/linux-csgo-external#28]
Are you able to get untrusted for the triggerbot? I have been using this and the other cheats this is based off on for sometime. But, have never used the triggerbot except for in community servers.

**Comment by faminee** [comment]
I'm pretty sure you can get untrusted on any server...
It won't untrust you.

**Comment by owerosu** [comment]
Afaik, untrusted ban is a ban from server side anti-cheat.
You shouldn't get untrusted using this hack.
However, you could get an overwatch ban which is a community ban.

**Comment by ghost** [comment]
@MrWhiteGoat I'm pretty sure you can only get untrusted bans on official Valve servers (deathmatch, casual, competitive, etc)

**Comment by faminee** [comment]
@Arvife Oh didn't knew that.

**Comment by ghost** [comment]
Yeah untrusted bans are only on Deathmatch/casual/competitive/etc. This is mostly for triggerbots under around 25ms response and invaild angles ( bad spin bots and bad aimbots ) and unclamped angles ( very bad aimbots ) Just didn't know if untrusted bans work on linux.

**Comment by Superchet** [comment]
Close issue plz
