### ISSUE TITLE
Trigger bot broken

### ISSUE THREAD

**Issue by Goldstrikerz** [McSwaggens/linux-csgo-external#30]
Need new offsets for CrossHairID

**Comment by Superchet** [comment]
Again?

**Comment by Superchet** [comment]
There hasn't been update, though

**Comment by Superchet** [comment]
Nope, works just fine. :)

**Comment by McSwaggens** [comment]
Triggerbot works just fine, make sure you have updated the hack.

`cd linux-csgo-external`
`git pull`
`make`
