### ISSUE TITLE
Library issue

### ISSUE THREAD

**Issue by ghost** [McSwaggens/linux-csgo-external#31]
The README.md says to install `libconfig-dev` however that still causes this error while making the cheat `main.cpp:18:25: fatal error: libconfig.h++: No such file or directory`

Switching it to `libconfig++-dev` fixes it, I'm not sure if this error happens to anyone else but I figured I'd share what fixed it

**Comment by luk1337** [comment]
You might be right, I didn't really try it out on anything Debian / *buntu based.

**Comment by ghost** [comment]
I'm on Ubuntu 16.04.1 LTS so yeah, it's probably a Debian/*buntu thing

**Comment by luk1337** [comment]
I guess suggesting users to install libconfig++-dev is a better idea.
https://github.com/McSwaggens/linux-csgo-external/pull/32

**Comment by ghost** [comment]
PR got merged, closing
