### ISSUE TITLE
Low fov aimbot + ida

### ISSUE THREAD

**Issue by faminee** [McSwaggens/linux-csgo-external#33]
Ayy, I'm trying to make a low fov aimbot and I have a few questions.
1. How hard is ida?
2. Can I do this externally?
3. Can I get untrusted for using an aimbot?(no?)

**Comment by McSwaggens** [comment]
1. You don't exactly need IDA for an aimbot
2. Yes, but it's hard to do `externally`, you should move to `internals` if your interested in doing more complex stuff...
3. Nope, if you're on Linux it shouldn't be a problem.

Try and learn internals, [this](https://github.com/Snorflake/basehooklinux) should help.

**Comment by faminee** [comment]
Thx,I'm pretty new to CSGO hacks...

**Comment by Superchet** [comment]
1. Dunno how to use IDA
2. Of course, ekknod did it, as you saw in vc/vcaim
3. No, not on linux.

**Comment by Superchet** [comment]
Oh oops "/

**Comment by Superchet** [comment]
:/ sorry
