### ISSUE TITLE
error @ comp.

### ISSUE THREAD

**Issue by ghost** [McSwaggens/linux-csgo-external#34]
[ 40%] Building CXX object CMakeFiles/csgo_external.dir/logger.cpp.o
[ 60%] Building CXX object CMakeFiles/csgo_external.dir/remote.cpp.o
[ 80%] Building CXX object CMakeFiles/csgo_external.dir/main.cpp.o
/root/linux-csgo-external/main.cpp:18:25: fatal error: libconfig.h++: No such file or directory
compilation terminated.
CMakeFiles/csgo_external.dir/build.make:134: recipe for target 'CMakeFiles/csgo_external.dir/main.cpp.o' failed
make[2]: **\* [CMakeFiles/csgo_external.dir/main.cpp.o] Error 1
CMakeFiles/Makefile2:67: recipe for target 'CMakeFiles/csgo_external.dir/all' failed
make[1]: **\* [CMakeFiles/csgo_external.dir/all] Error 2
Makefile:83: recipe for target 'all' failed
make: **\* [all] Error 2

**Comment by McSwaggens** [comment]
`sudo apt-get install libconfig++-dev`

**Comment by ghost** [comment]
nothing happenS

**Comment by McSwaggens** [comment]
> nothing happenS 

I need a little more information, nothing happens when you try to install `libconfig++-dev` ?
Also, what _distro_ are you using?

**Comment by ghost** [comment]
k was my fault i change to arch linux sry for this but still [ERROR] I/O error while reading settings.cfg.
[ERROR] Cannot find property: 'keycodeGlow' in settings.cfg file
terminate called after throwing an instance of 'std::logic_error'
  what():  basic_string::_M_construct null not valid
Aborted
 some errors

**Comment by luk1337** [comment]
Do you actually have a settings.cfg file?

**Comment by McSwaggens** [comment]
Make sure the `settings.cfg` file is actually there.

Or re-download it with the command `wget https://raw.githubusercontent.com/McSwaggens/linux-csgo-external/master/settings.cfg`

**Comment by ghost** [comment]
yes its there but not working k hmm

**Comment by ghost** [comment]
the config file must be in the same folder where the hack is ok

**Comment by ghost** [comment]
now its working
