### ISSUE TITLE
error

### ISSUE THREAD

**Issue by ghost** [McSwaggens/linux-csgo-external#35]
[ERROR] I/O error while reading settings.cfg.
[ERROR] Cannot find property: 'keycodeGlow' in settings.cfg file
terminate called after throwing an instance of 'std::logic_error'
  what():  basic_string::_M_construct null not valid
I have settings.cfg in linux-csgo-external-master and build folder but it still doesn't work

**Comment by McSwaggens** [comment]
Have you tried re-downloading it?
Also make sure the permissions are correct.

**Comment by ghost** [comment]
Yes i tried by still doesnt work

**Comment by Hartbook** [comment]
Move the executable from build directory to its parent directory (where settings.cfg is located).

**Comment by ghost** [comment]
@Hartbook @McSwaggens I change permissions for csgo_external and settings.cfg and i copied csgo_external to main folder but still error with settings.cfg

**Comment by ghost** [comment]
I download hack from luk and it works fine

**Comment by Superchet** [comment]
Odd, anyways. Pretty sure you can close it now

**Comment by ghost** [comment]
Sorry but i must open second time. Hack working for me 2hours and now i have the same problem.

**Comment by McSwaggens** [comment]
Did you download the hack as your own user? root?
Try re-downloading the hack and using the `make` command and not `cmake .`

**Comment by newchild** [comment]
Post your config file

**Comment by INeedHelpNoob** [comment]
Put your config file into the build folder
