### ISSUE TITLE
Failed to read glowClassAddress

### ISSUE THREAD

**Issue by ghost** [McSwaggens/linux-csgo-external#36]
Hello! 
Things were working great until the very recent update. Now the log says:

[ADDRESS] Glow function:     [0x0]
[ADDRESS] Glow array pointer:    [0x0]

and, lower down,

[ERROR] Failed to read glowClassAddress
[ERROR] An error occurred, closing...

Is this something I can update and fix? I'd love to learn more.

**Comment by WolverinDEV** [comment]
The last csgo update beaks that.

**Comment by dojigger** [comment]
Due to the fact that the problem concerns glow addresses, will fixing it be a hard job?
I tried to research the problem, are there others that know what's wrong?

**Comment by McSwaggens** [comment]
Apologies in advance, due to the fact that @luk1337 and I are creating an internal hack (to be released in a couple of days) I am unable to work on updating the current hack, if anyone wants to update the `glow address` I'll accept the pull request into this branch, until then I'd keep a look out on the forum for our release.
Now I'll just tease you with [these screenshots](http://imgur.com/a/wVLgK) :joy: :ok_hand: :100:

**Comment by dojigger** [comment]
@McSwaggens Just a brief question, will the internal cheat be injectable on linux?

**Comment by McSwaggens** [comment]
It's a Linux only hack, so yes :)

**Comment by dojigger** [comment]
Great! So it will include an anti-aim? Have you considered something like emotion and will the character be backwards to make it good for hvh?

**Comment by McSwaggens** [comment]
The UI is not even half done (literally the last thing that needs finishing) but the spin options we will have are

``` C++
SPIN_FAST,
SPIN_SLOW,
JITTER,
SIDE,
BACKWARDS
```

**Comment by dojigger** [comment]
Really cool, I am looking forward to that. However, will the project be totally open once it has been released?

**Comment by luk1337** [comment]
Yes.

**Comment by dojigger** [comment]
Do you by any chance need people test this cheat? :)

**Comment by luk1337** [comment]
No.

**Comment by ghost** [comment]
(Not sure if this is the best place to discuss this topic), but @luk1337, will the internal cheat be regularly maintained or is it just one of your projects? Futhermore, will it be on your github and do you know about the release date? Thanks!

**Comment by faminee** [comment]
Wow insane. I was trying to create something like this but did nothing compared to this.

**Comment by luk1337** [comment]
@aeroch:
It wil be fully OSS, I have no clue how long it will be supported for but we'll do whatever we can.
We don't have a strict release date so we'll release it /when it's ready/.

**Comment by ghost** [comment]
@McSwaggens @luk1337 : 
The idea of this really took my fancy. Can you tell if it'll be finished after weeks, months or will it take longer?

**Comment by luk1337** [comment]
We will try to deliver it within 2~4 weeks.

**Comment by luk1337** [comment]
Might be earlier than that, who knows.

**Comment by faminee** [comment]
@luk1337 is it possible to get src rn or you will only release when it's "ready"?

**Comment by luk1337** [comment]
No it is not, we'll release the source once it's ready. We don't plan to do any binary releases.

**Comment by faminee** [comment]
Pretty sure anyone who uses linux can compile it.
Gl. Will be looking forward for this.

**Comment by ghost** [comment]
I will install manjaro only for this purpose! I use ubuntu on regular basis but I cannot get build-tools to work and hence cannot do compiles. Would have loved to see binary releases because of that but oh well. :)

**Comment by faminee** [comment]
@aeroch I might be able to get you a binary release. I can't wait for the spinbot :+1:

**Comment by ghost** [comment]
@MrWhiteGoat That'd be great, thanks in advance but let's see when the source has been released. Maybe I can get everything working. But yep, this project is something I have been looking for a long time, tried coding myself but haven't finished anything due to my limited knowledge on C/C++.

**Comment by McSwaggens** [comment]
@aeroch I don't see it taking longer than a week, although who knows, I'm a perfectionist, I wont release a half done project.

**Comment by faminee** [comment]
@McSwaggens thanks man. I tried coding this like @aeroch did but failed due to my limited knowledge.
I'm really new to gamehacking with c++. If this was java lol

**Comment by WolverinDEV** [comment]
@McSwaggens can you please update the memory pattern?
Maybe i can give you some money for this quick work

**Comment by faminee** [comment]
Anyway you can use the low fov on faceit?

**Comment by ghost** [comment]
@WolverinDEV Yup, this issue post went a bit off-topic. Is there anyone that can fix the `glow addresses`?

**Comment by ericek111** [comment]
Woo, I'm really excited about that internal hax. Hopefully it'll come with a nice SDK, so we can port 1337 features from Windows. :P

**Comment by faminee** [comment]
Yup. As soon as this comes out i'm adding a ton of shit(unless they do everything for me lol)

**Comment by jessemies** [comment]
Anyone fixing the trigger and walls? I need some cheats on linux!

**Comment by MrWhiteGoat** [comment]
@jessemies Change the offsets.

**Comment by faminee** [comment]
@jessemies will fix in a min.

**Comment by ghost** [comment]
@MrWhiteGoat Did you find the offsets yet? I tried and I failed. Not sure why.

**Comment by faminee** [comment]
@aeroch Didn't find any yet.
Might as well wait for the internal.

**Comment by ghost** [comment]
@MrWhiteGoat Yup, the trigger was a really cool project but wasn't all that useful. I am pretty sure people have to wait for the internal and I am pretty sure it'll be something magnificent.

**Comment by WolverinDEV** [comment]
I tried it to but i cant recreate a new memory pattern. Im currently tring this with a smal project

**Comment by Superchet** [comment]
Guys, check Aimtux.net daily to see if we've released yet.

**Comment by faminee** [comment]
@aeroch Yeah can't wait. I just need an okay SDK to start my internals.

**Comment by ghost** [comment]
This blew up. Good info guys, and the internal sounds really great. Thanks!

**Comment by Superchet** [comment]
Eyo, White, reply to my email

**Comment by Superchet** [comment]
White, http://pastebin.com/RrMXZNY4
You'll need offset rolling, though

**Comment by faminee** [comment]
@Superchet offset rolling?

**Comment by Superchet** [comment]
Yes

**Comment by sKuhLight** [comment]
Someone got it work again?

I tried out some Internal Stuff i found, only the Skinchanger is working for me. 
Found 2 BaseHooks, both Crashes the game.

**Comment by faminee** [comment]
What you using to inject?

**Comment by sKuhLight** [comment]
Im Injecting with https://github.com/gaffe23/linux-inject .

I will test it out again, because the skinchanger injection is working.

**Comment by faminee** [comment]
Yeah known problem. Inject with GDB instead.

**Comment by sKuhLight** [comment]
Oh ok :)
Uhm I never used GDB, do you got a link to a quick instruction how to inject so's with it?

**Comment by faminee** [comment]
http://pastebin.com/B0anrGgX
Basically in order.
use "call $dlclose" when unloading the library.

**Comment by sKuhLight** [comment]
Thanks  :) Injection seems working. But no function ingame, esp still off. 
I will try the second so i got :)

**Comment by faminee** [comment]
You got the new offsets?

**Comment by sKuhLight** [comment]
No, thehe. I thought thats the problem, but im not familiar with getting offsets using IDA.
I searched for offsets in some forums, but not found :/

Do you got the offsets and maybe share them with me? :)

**Comment by faminee** [comment]
Didn't find them yet, though I'm pretty sure you can use an offset dumper. Search it up :)

**Comment by sKuhLight** [comment]
There is an Offsetdumper for linux? :o 
I searched for it but never found one o_O

**Comment by faminee** [comment]
https://github.com/Y3t1y3t/CSGO-Dumper

**Comment by McSwaggens** [comment]
That's a Windows offset dumper lol, it won't work.

**Comment by faminee** [comment]
Oh xd
My fault.

**Comment by sKuhLight** [comment]
Haha :D I searched a long time for an Offset Dumper on Linux, never found something.

**Comment by ghost** [comment]
Btw, since you're working on the internal, don't you got the offsets then? Or did you go the other way? :p

**Comment by faminee** [comment]
@aeroch Yeah, he should have them.
@McSwaggens can you update us like daily about the internals. #InternalHype

**Comment by ghost** [comment]
@MrWhiteGoat @McSwaggens I am also so hyped. Is the aimtux page legit,t though? I check it every now and then.

**Comment by McSwaggens** [comment]
@aeroch  "AimTux page"?

@MrWhiteGoat We've got a NetVar manager, it allows us to fetch the offsets by name.

**Comment by sKuhLight** [comment]
@MrWhiteGoat The Method u send me for Inject doesnt work :O Tested it with the skinchanger and it isnt working.

But with the Injector the so is working :/

**Comment by McSwaggens** [comment]
@sKuhLight have a look at [this](https://aixxe.net/2016/09/shared-library-injection)

**Comment by sKuhLight** [comment]
@McSwaggens Okey :) I'll post when i finished :D

**Comment by faminee** [comment]
@McSwaggens It's basically what I gave him ;-;
Will you release the netvar manager too?

**Comment by ghost** [comment]
AimTux page, an url someone posted here a while back and said it was for this project.

**Comment by McSwaggens** [comment]
https://github.com/McSwaggens/AimTux <-- this?
It'll be opened up soon, just need to iron out some bugs and finish UI.

**Comment by ghost** [comment]
Not on github, but a proper url. Not on pc so cannot remember but i think it was aimtux.net.

**Comment by faminee** [comment]
@McSwaggens nice man. Release date?

**Comment by McSwaggens** [comment]
@MrWhiteGoat In a couple of days, it'll be done when it's done.

**Comment by ghost** [comment]
Just take your time and make it good. But just my final question, how will injection be implemented? Do we have to use GDB or similar?

**Comment by Superchet** [comment]
Yeah. gdb or hotpatcher, own choice

**Comment by faminee** [comment]
@McSwaggens Okay nice. Can't wait for release. 100% going to help you guys out with features, bugs, etc when it comes out.

**Comment by Superchet** [comment]
MrWhiteGoat, that's the thing. Only releasing when there are 100% no bugs and McSwaggens is satisfied

**Comment by ghost** [comment]
Ok, have get more into it now since I havent done linux injections that much.

**Comment by McSwaggens** [comment]
I'm currently using a GDB script from [Aixxes website](https://aixxe.net/2016/09/shared-library-injection)

**Comment by Superchet** [comment]
hotpatcher -l $(pwd)/aimtux-csgo.so -vvv $(pidof csgo_linux64)
or check out gdb on aixxe.net

**Comment by faminee** [comment]
Yeah. I need to start using a script instead of manually typing GDB.

**Comment by McSwaggens** [comment]
Any of you good at web dev?

**Comment by faminee** [comment]
@McSwaggens I can probably get a friend to do it. What you need?

**Comment by ghost** [comment]
That is something to be done. I used to manually inject in terminal when I would do some assaultcube stuff. Lol

**Comment by Superchet** [comment]
Ayy assaultcube XD

**Comment by ghost** [comment]
I have done some pages. I handle styling very well but cannot do javascript. I could make a theme.

**Comment by faminee** [comment]
I'm really new to internals, and it doesn't help that every guide, docs out there is for windows.
Anyone have any resources?

**Comment by ghost** [comment]
Aixxe is the guy to resort to.

**Comment by McSwaggens** [comment]
Internals are pretty much exactly the same as on Windows, only problem you guys will have is navigating the huge project lol

**Comment by Superchet** [comment]
1. http://www.unknowncheats.me/forum/counterstrike-global-offensive/181878-linux-basehook.html
2. https://github.com/aixxe/csgo-skinchanger-linux
3. aixxe.net

**Comment by faminee** [comment]
@Superchet you have cracked IDA?

**Comment by Superchet** [comment]
https://aixxe.net/2016/09/linux-skin-changer
https://aixxe.net/2016/09/createmove-linux-csgo

**Comment by Superchet** [comment]
No, sorry

**Comment by faminee** [comment]
Ah k, I did do createmove, etc. Though I got stuck trying to find enemies ;-;

**Comment by sKuhLight** [comment]
Im back, CS:GO directly chrashes when i call gdb and attach the process

```
warning: Could not load shared library symbols for bin/linux64/launcher_client.so.
Do you need "set solib-search-path" or "set sysroot"?
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/lib/x86_64-linux-gnu/libthread_db.so.1".
0x00007fa19596a52e in __pthread_mutex_unlock_usercnt (decr=1, mutex=0x782d800) at pthread_mutex_unlock.c:55
55  pthread_mutex_unlock.c: Datei oder Verzeichnis nicht gefunden.
(gdb) 

```

@McSwaggens Last time i Created a Homepage was 3 years ago. I can create a whole Layout with Html and CSS, but not code php etc.

**Comment by ghost** [comment]
@sKuhLight i have more recent experience but php is not mu cuppa tea either. We could team up and find a php and javascript expert to make a site if @McSwaggens needs one.

**Comment by sKuhLight** [comment]
@aeroch I have a friend whos really good at codin, php and javascript also.
Can ask him, maybe he have time :D

**Comment by faminee** [comment]
@sKuhLight you need to put in "continue"
It doesn't crash.

**Comment by ghost** [comment]
Ok great. When I am back home, I can design a basic template and upload it.

**Comment by sKuhLight** [comment]
@MrWhiteGoat  Oops, I will try it out wait :)

@aeroch  Okey :) We should create a skype group or something.

**Comment by ghost** [comment]
@sKuhLight lets decide later. If you want to talk, I am really often on teamspeak but skupe is fine too, for text chat.

**Comment by ericek111** [comment]
I asked for a Slack channel dedicated to Linux (unknowncheats.slack.com).

I can help you with coding the website (if you provide design).

This thread is pure gold.

**Comment by faminee** [comment]
Yes. I can't web dev for my life so I'm waiting for release to help out.

**Comment by McSwaggens** [comment]
> This thread is pure gold.

Agreed, this has blown up in my face.

**Comment by faminee** [comment]
Yup. This is going to be unreal.

**Comment by ghost** [comment]
Haha. Rhis started off as a bug report but now it's a real thread itself.

Slack'd be great!

**Comment by faminee** [comment]
@McSwaggens Change labels?

**Comment by sKuhLight** [comment]
@MrWhiteGoat  It worked :D Sometimes I'm so fcking brainless. .-.

@aeroch We can use both. I got a Teamspeak Server we can use, "84.200.105.68" the rest of u is welcome too  :)

**Comment by ericek111** [comment]
What about FB group? Add me plz - **\* - discord will do just fine

**Comment by faminee** [comment]
@sKuhLight dw man. When I started with GDB, I did the same mistake :))

Guys how about discord group?

**Comment by ghost** [comment]
Ok. I will start working on something after 2 hours. Have to install a new toilet seat. :D

**Comment by sKuhLight** [comment]
@MrWhiteGoat  Haha okey :3

DIscord is fine, too. But on my ts we can share files easy.

**Comment by faminee** [comment]
I literally can't wait for this. Plz release src ;)

@sKuhLight Yeah sure. I can't voice half the time atm though.

When this is released we should do premade games of full on spinbotting :)

**Comment by ericek111** [comment]
Discord channel: https://discord.gg/9mX9N

**Comment by sKuhLight** [comment]
@MrWhiteGoat  Haha :D We can do, but then i need a smurf xD

**Comment by faminee** [comment]
I'm doing this on my main We won't get banned if we don't get over 11reports so.

**Comment by sKuhLight** [comment]
I wont try out this risk xD

**Comment by faminee** [comment]
@sKuhLight I can prob get you a smurf to play on for a day.
It's my friends alt so you can't use it all the time.

**Comment by sKuhLight** [comment]
@MrWhiteGoat  That would be nice :) Yeah its no Problem, i will buy a smurf soon, but im to lazy xD

Do u wanna add me in steam? /id/senpai_loves_u/

**Comment by faminee** [comment]
@sKuhLight Adding.

**Comment by ghost** [comment]
Well guys, I have 6 accounts 2 of which I can lend. So when the src is public, I can give you credentials if you need.

**Comment by faminee** [comment]
@aeroch okay nice. Might use one instead of risking a knife...

**Comment by ghost** [comment]
Btw @McSwaggens how did you learn C++? CSGO cheats alone and the overall need for coding got me thinking of studying it more profoundly. I handle some things but not as a whole.

**Comment by faminee** [comment]
@aeroch trying to do the same here. I have like 3-4 years of java experience, but never really did C++.
Learned the basics, etc in a day. But need to learn it better.

**Comment by ericek111** [comment]
I have 1 spare acc (besides my smurf and main).

I learned Java by coding Bukkit plugins and Minecraft mods (ya can see my lixkopack repo) and J2ME apps for my C905. C++ by coding hax and microcontrollers.

**Comment by ghost** [comment]
I am taking my math finals in Feb so I am thinking of applying for programming courses at Uni but not sure. Internet is full of tutorials but I am not sure if those can give "perfect" skills.

**Comment by faminee** [comment]
@ericek111 teach me about virtual methods really fast yeah? Is it like injection in java?(javassist, etc)

**Comment by faminee** [comment]
Does any of you have private repos?

**Comment by ericek111** [comment]
Check out the Discord channel - https://discord.gg/9mX9N. We are trying to do some shit.

**Comment by McSwaggens** [comment]
@owerosu fixed glow signature, rejoice.
