### ISSUE TITLE
undefined reference to `libconfig::Setting::operator std::string() const'

### ISSUE THREAD

**Issue by ghost** [McSwaggens/linux-csgo-external#39]
$ make
c++ _.cpp *.h -Wunused -std=gnu++11 -lX11 -lconfig++ -o csgo_external
hack.cpp: In function ‘void hack::Glow(double_, remote::Handle_, remote::MapModuleMemoryRegion_)’:
hack.cpp:101:49: warning: pointer of type ‘void _’ used in arithmetic [-Wpointer-arith]
       csgo->Read((void_) (g_glow[i].m_pEntity + 0x94), &entityId, sizeof(int));
                                                 ^
/tmp/ccfqZMRR.o: In function `getConfigValue(std::string)':
main.cpp:(.text+0x3f): undefined reference to`libconfig::Setting::operator std::string() const'
/usr/lib/gcc/x86_64-linux-gnu/4.8/../../../x86_64-linux-gnu/libconfig++.so: undefined reference to `VTT for std::__cxx11::basic_stringstream<char, std::char_traits<char>, std::allocator<char> >@GLIBCXX_3.4.21'
/usr/lib/gcc/x86_64-linux-gnu/4.8/../../../x86_64-linux-gnu/libconfig++.so: undefined reference to`std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >::_M_create(unsigned long&, unsigned long)@GLIBCXX_3.4.21'
/usr/lib/gcc/x86_64-linux-gnu/4.8/../../../x86_64-linux-gnu/libconfig++.so: undefined reference to `std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >::_M_replace(unsigned long, unsigned long, char const*, unsigned long)@GLIBCXX_3.4.21'
/usr/lib/gcc/x86_64-linux-gnu/4.8/../../../x86_64-linux-gnu/libconfig++.so: undefined reference to`vtable for std::__cxx11::basic_stringbuf<char, std::char_traits<char>, std::allocator<char> >@GLIBCXX_3.4.21'
/usr/lib/gcc/x86_64-linux-gnu/4.8/../../../x86_64-linux-gnu/libconfig++.so: undefined reference to `vtable for std::__cxx11::basic_stringstream<char, std::char_traits<char>, std::allocator<char> >@GLIBCXX_3.4.21'
/usr/lib/gcc/x86_64-linux-gnu/4.8/../../../x86_64-linux-gnu/libconfig++.so: undefined reference to`std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >::_M_assign(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&)@GLIBCXX_3.4.21'
/usr/lib/gcc/x86_64-linux-gnu/4.8/../../../x86_64-linux-gnu/libconfig++.so: undefined reference to `std::__cxx11::basic_stringstream<char, std::char_traits<char>, std::allocator<char> >::~basic_stringstream()@GLIBCXX_3.4.21'
collect2: error: ld returned 1 exit status
make: **\* [run] Error 1

**Comment by faminee** [comment]
You need to install libconfigdev.

**Comment by ghost** [comment]
I have it installed.

**Comment by McSwaggens** [comment]
`sudo apt-get install libconfig++-dev`

**Comment by ghost** [comment]
https://puu.sh/rDeDk.png

**Comment by ghost** [comment]
I made a mod just to not have to use that extra library that causes me problems.
http://pastebin.com/piDbBTiL

**Comment by McSwaggens** [comment]
Sorry for commenting on closed issue, but are you sure the `settings.cfg` is in the same location as the binary? and are you executing linux-csgo-external from within that directory?

**Comment by ghost** [comment]
It is when compiled, not when running. And yes, I have the "settings.cfg" in the same directory, this library because I'm no errors. Anyway, as I made a small change to do not use that library.
