### ISSUE TITLE
Triggerbot broken

### ISSUE THREAD

**Issue by rpasta42** [McSwaggens/linux-csgo-external#4]
New update also broke the triggerbot. I attempted to fix it [here](https://github.com/rpasta42/linux-csgo-external/blob/master/hack.cpp#L137).

I basically hoped that address change won't be too far away, and I added a loop for testing different offsets, and printing the value of crossHairId and entityId. 

I figured out that crossfair offset has changed by 0x10, so I just added 10 to the address "csgo->Read((void*) (localPlayer+0xB370 + 0x10)"

I haven't yet found new entityId offset, so I removed the check (crossHairId == entityId). My temporary fix makes the triggerbot work by shooting anything that has crossHairId != 0, which also makes it shoot teammates.

My changes uses extremely ugly and inconsistent mix of tabs and spaces, and a lot of dirty code, so they should probably not get merged into main branch.

I'm thinking of making a github repo with a list of actively maintained Counter Strike hacks for Linux. There's been several forks of original repo, but all of them get abandoned after a while. As far as I know, this is the only actively maintained fork.

**Comment by McSwaggens** [comment]
Nice job, I've added an updated [Entity struct](https://github.com/McSwaggens/linux-csgo-external/blob/master/types.h#L23) you can have a look at, it also includes an `m_iEntityId` integer.
If you add those fixes try and push it into the main branch!

**Comment by McSwaggens** [comment]
Trigger bot has been fixed in [this commit](https://github.com/McSwaggens/linux-csgo-external/commit/3036f59efc9682d58446845ffc5426ad196c04eb)
Thanks for the help! :100:

**Comment by rpasta42** [comment]
Awesome, I'm glad to be slightly useful!
