### ISSUE TITLE
can not be compile

### ISSUE THREAD

**Issue by elffoam** [McSwaggens/linux-csgo-external#47]
When i try make, i receive error:
undefined reference to `libconfig::Setting::operator std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >() const'

elff@debian:~/workspace$  cd /home/elff/workspace/linux-csgo-external
elff@debian:~/workspace/linux-csgo-external$ make
c++ *.cpp *.h -Wunused -std=gnu++11 -lX11 -lconfig++ -o csgo_external
hack.cpp: In function 'void hack::Glow(double*, remote::Handle*, remote::MapModuleMemoryRegion*)':
hack.cpp:101:47: warning: pointer of type 'void *' used in arithmetic [-Wpointer-arith]
       csgo->Read((void*) (g_glow[i].m_pEntity + 0x94), &entityId, sizeof(int));
                           ~~~~~~~~~~~~~~~~~~~~^~~~~~
/tmp/ccSmz1iD.o: In function `getConfigValue(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >)':
main.cpp:(.text+0x41): undefined reference to `libconfig::Setting::operator std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >() const'
collect2: error: ld returned 1 exit status
Makefile:2: recipe for target 'run' failed
make: *** [run] Error 1

**Comment by McSwaggens** [comment]
Use [AimTux](https://github.com/AimTuxOfficial/AimTux)
