### ISSUE TITLE
Triggerbot

### ISSUE THREAD

**Issue by AntoninataRiech** [McSwaggens/linux-csgo-external#5]
Trigger still aims on teammates.

**Comment by McSwaggens** [comment]
Has it always been like that? or is this a new bug?

**Comment by AntoninataRiech** [comment]
New bug. That's why rpasta42 said it was semi-working.

**Comment by AntoninataRiech** [comment]
I'll see what happened and try to fix it

**Comment by McSwaggens** [comment]
Problem has to do with the local player team offset

**Comment by AntoninataRiech** [comment]
Yeah, besides that, could you remove the Pinky-ish glow? I hate having to manually do it everytime

**Comment by AntoninataRiech** [comment]
Thx

**Comment by McSwaggens** [comment]
>Could you remove the Pinky-ish glow?
Fixed in [this commit](https://github.com/McSwaggens/linux-csgo-external/commit/e1195f4d8476f8c03c976c5bace6d8498e365980)

**Comment by McSwaggens** [comment]
Going to work on the trigger bot tomorrow,
very interesting bug... :imp:

**Comment by Not2EXceL** [comment]
m_iEntityId == 0x94
if m_iCrosshairId == m_iEntityId //fire

**Comment by McSwaggens** [comment]
Trigger bot bug fixed in [this commit](https://github.com/McSwaggens/linux-csgo-external/commit/159ad22a8f091fa2a559dd45837eeeccaa678530)  :100:
