### ISSUE TITLE
Toggle key don't work

### ISSUE THREAD

**Issue by yukoulah** [McSwaggens/linux-csgo-external#6]
I am running on fedora, GlowEsp work fine, but F6,F7,F8 do nothing. My bindkey to.

log: `Hack loaded...`
- Num lock off ;)
- libXext-devel installed (without it don't compile: "XTest.h: File or Directory not Found")

**Comment by ghost** [comment]
do you check is num lock on ? when num lock on that dont work :D

**Comment by McSwaggens** [comment]
Have you got `libxtst-dev` installed?
`sudo apt-get install libxtst-dev`

**Comment by yukoulah** [comment]
yes... 
`sudo dnf list installed | grep libx

libxcb.i686                            1.11.1-2.fc24            @fedora
libxcb.x86_64                          1.11.1-2.fc24            @koji-override-0
libxcb-devel.x86_64                    1.11.1-2.fc24            @fedora
libxdo.x86_64                          1:3.20150503.1-2.fc24    @fedora
libxkbcommon.i686                      0.6.1-1.fc24             @updates
libxkbcommon.x86_64                    0.6.1-1.fc24             @updates
libxkbcommon-devel.x86_64              0.6.1-1.fc24             @updates
libxkbcommon-x11.x86_64                0.6.1-1.fc24             @updates
libxkbcommon-x11-devel.x86_64          0.6.1-1.fc24             @updates
libxkbfile.x86_64                      1.0.9-3.fc24             @koji-override-0
libxkbfile-devel.x86_64                1.0.9-3.fc24             @fedora
libxklavier.x86_64                     5.4-6.fc24               @koji-override-0
libxml++.i686                          2.40.1-2.fc24            @fedora
libxml++.x86_64                        2.40.1-2.fc24            @fedora
libxml2.i686                           2.9.3-3.fc24             @fedora
libxml2.x86_64                         2.9.3-3.fc24             @koji-override-0
libxml2-devel.x86_64                   2.9.3-3.fc24             @fedora
libxshmfence.i686                      1.2-3.fc24               @fedora
libxshmfence.x86_64                    1.2-3.fc24               @koji-override-0
libxslt.x86_64                         1.1.28-12.fc24           @koji-override-0
mesa-libxatracker.x86_64               12.0.1-1.fc24            @updates
python3-libxml2.x86_64                 2.9.3-3.fc24             @koji-override-0`

**Comment by luk1337** [comment]
You need libXtst-devel package.

**Comment by McSwaggens** [comment]
Your list doesn't include any `libxtst`
When running: `/sbin/ldconfig -p | grep libXtst.so`
for me it returns:

```
libXtst.so.6 (libc6,x86-64) => /usr/lib/x86_64-linux-gnu/libXtst.so.6
libXtst.so.6 (libc6) => /usr/lib/i386-linux-gnu/libXtst.so.6
libXtst.so (libc6,x86-64) => /usr/lib/x86_64-linux-gnu/libXtst.so
```

**Comment by yukoulah** [comment]
`/sbin/ldconfig` -p | grep `libXtst.so`
returns for me
`libXtst.so.6` (libc6,x86-64) => `/lib64/libXtst.so.6`
`libXtst.so.6` (libc6) => `/lib/libXtst.so.6`

**Comment by luk1337** [comment]
This is what it returns here ( binds are working here ).

```
luk@luk-pc:~$ /sbin/ldconfig -p | grep libXtst.so
    libXtst.so.6 (libc6,x86-64) => /lib64/libXtst.so.6
    libXtst.so.6 (libc6) => /lib/libXtst.so.6
    libXtst.so (libc6,x86-64) => /lib64/libXtst.so
    libXtst.so (libc6) => /lib/libXtst.so
```

**Comment by yukoulah** [comment]
How can I do binds? :/

Thx for answers

**Comment by McSwaggens** [comment]
The key system was recently redone, try pulling and try again?

**Comment by yukoulah** [comment]
Thx guys, this is done. (after repulling)

**Comment by McSwaggens** [comment]
Done? Could you get it to work?

**Comment by yukoulah** [comment]
Yes, all is working fine, thx

**Comment by AntoninataRiech** [comment]
Then close it?
