### ISSUE TITLE
pink outlines on players?

### ISSUE THREAD

**Issue by nopenothingever** [McSwaggens/linux-csgo-external#7]
I know that you added pink esp for items but players have a pink outline for me more often than not than the old red/blue outlines appear for me. Lubuntu 14.04.05 with ati open source driver

**Comment by McSwaggens** [comment]
Fixed in [this commit](https://github.com/McSwaggens/linux-csgo-external/commit/e1195f4d8476f8c03c976c5bace6d8498e365980)
