### ISSUE TITLE
TriggerKey Not working 

### ISSUE THREAD

**Issue by doodfate** [McSwaggens/linux-csgo-external#9]
The TriggerKey dose not seem to work for me at all!
I binded it to h in game (bind "h" "+alt") and it dose not work, everything else in the hack work like a charm!  
Is this problem just because I am ignorant or did i do the bind wrong?
plz help me fix :) because I suck at the game :)

**Comment by yukoulah** [comment]
"+alt1" not "+alt"

**Comment by doodfate** [comment]
O ok ill give it a try 
thx for the quick response :)

**Comment by doodfate** [comment]
O ops typo it was +alt1

**Comment by doodfate** [comment]
And it is working thx
